/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import classes.Alugado;
import util.Util;
import classes.Cliente;
import classes.Veiculo;
import dao.AlugadosDAO;
import dao.ClienteDAO;
import dao.VeiculoDAO;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author elvis
 */
public class frmClientes extends javax.swing.JFrame {

    public frmClientes() {
        initComponents();
        abas.setEnabledAt(1, false);
    }

    private Veiculo gVeiculo = new Veiculo();
    private Alugado gAlugados = new Alugado();
    private Cliente gCliente = new Cliente();

    private boolean edicaoAtiva = false;

    private String[] dataAluguel(int qtdDias) {
        Date dt = new Date();
        Calendar c = Calendar.getInstance();
        c.setTime(dt);
        c.add(Calendar.DATE, qtdDias);
        dt = c.getTime();

        SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");

        String[] xs = new String[]{formatador.format(dt), formatador.format(new Date())}; //added []

        return xs;
    }

    private void montaAlugados() {
        Float precoTotal = gVeiculo.getPrecoDia() * (cbQtd.getSelectedIndex() + 1);
        String[] data = dataAluguel(cbQtd.getSelectedIndex() + 1);

        lbTotal.setText("R$" + precoTotal);

        // Seta possiveis datas
        gAlugados.setDataAluguel(data[1]);
        gAlugados.setDataRetorno(data[0]);
        // Outros
        gAlugados.setPrecoTotal(precoTotal);
        gAlugados.setPlaca(gVeiculo.getPlaca());
        gAlugados.setCpf(gCliente.getCpf());
    }

    private void resetCampos() {
        txtNome.setText("");
        cbSexo.setSelectedItem("M");
        txtCEP.setText("");
        txtRua.setText("");
        txtBairro.setText("");
        txtNumero.setText("");
        txtComplemento.setText("");
        txtCidade.setText("");
        txtEstado.setText("");
        txtEmail.setText("");
        txtCelular.setText("");

        txtCPF.setEnabled(true);
    }

    private void modoEdicao(boolean status) {
        txtCPF.setEnabled(!status);

        txtNome.setEnabled(status);
        cbSexo.setEnabled(status);
        txtCEP.setEnabled(status);
        txtRua.setEnabled(status);
        txtBairro.setEnabled(status);
        txtNumero.setEnabled(status);
        txtComplemento.setEnabled(status);
        txtCidade.setEnabled(status);
        txtEstado.setEnabled(status);
        txtEmail.setEnabled(status);
        txtCelular.setEnabled(status);
    }

    private Cliente gravaCliente() {
        Cliente gravaCli = new Cliente();
        Util map = new Util();

        gravaCli.setCpf(map.parserCpf(txtCPF.getText()));
        gravaCli.setNome(txtNome.getText());
        gravaCli.setSexo(cbSexo.getSelectedItem().toString());
        gravaCli.setCep(txtCEP.getText());
        gravaCli.setRua(txtRua.getText());
        gravaCli.setBairro(txtBairro.getText());
        gravaCli.setNumero(txtNumero.getText());
        gravaCli.setComplemento(txtComplemento.getText());
        gravaCli.setCidade(txtCidade.getText());
        gravaCli.setEstado(txtEstado.getText());
        gravaCli.setEmail(txtEmail.getText());
        gravaCli.setCelular(map.parserCelular(txtCelular.getText()));

        btnAlugar.setEnabled(false); // Desabilita aluguel
        mnAlugar.setEnabled(false); // Desabilita aluguel
        return gravaCli;
    }

    public void enviaAlugado(Veiculo veiculo) {
        this.setTitle("Aluguel de veículo");

        gVeiculo = veiculo;

        lbPlaca.setText("Placa: " + veiculo.getPlaca());

        lbModelo.setText(veiculo.getModelo());
        lbMarca.setText(veiculo.getMarcaStr());
        lbClasse.setText(veiculo.getClasse());
        lbCor.setText(veiculo.getCor());
        lbAno.setText(veiculo.getAno());
        lbCategoria.setText(veiculo.getCategoria());
        lbPortas.setText(veiculo.getPortas().toString());

        lbValor.setText("R$" + veiculo.getPrecoDia());
        lbTotal.setText("R$" + veiculo.getPrecoDia());

        abas.setEnabledAt(1, true);

        montaAlugados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbPlaca = new javax.swing.JLabel();
        abas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCEP = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCarros1 = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        txtEstado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtRua = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JLabel();
        txtCPF = new javax.swing.JFormattedTextField();
        cbSexo = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        txtNumero = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lbAno = new javax.swing.JLabel();
        lbCor = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lbClasse = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lbMarca = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbCategoria = new javax.swing.JLabel();
        lbTotal = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lbModelo = new javax.swing.JLabel();
        btnAlugar = new javax.swing.JButton();
        lbPortas = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        cbQtd = new javax.swing.JComboBox<>();
        lbValor = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnCadastrar = new javax.swing.JMenuItem();
        mnAlterar = new javax.swing.JMenuItem();
        mnCancelar = new javax.swing.JMenuItem();
        mnAlugar = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes");
        getContentPane().setLayout(null);

        lbPlaca.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbPlaca.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(lbPlaca);
        lbPlaca.setBounds(450, 10, 290, 50);

        abas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        abas.setMaximumSize(new java.awt.Dimension(10000, 32767));
        abas.setOpaque(true);

        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentHidden(evt);
            }
        });
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("CPF:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 20, 50, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("CEP:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 100, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Email:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(320, 180, 50, 30);

        txtCEP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCEPActionPerformed(evt);
            }
        });
        txtCEP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCEPKeyTyped(evt);
            }
        });
        jPanel1.add(txtCEP);
        txtCEP.setBounds(80, 100, 150, 30);

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(370, 180, 320, 30);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Bairro:");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(430, 60, 50, 30);

        txtBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        txtBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBairroKeyTyped(evt);
            }
        });
        jPanel1.add(txtBairro);
        txtBairro.setBounds(490, 60, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nome:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 20, 50, 30);

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeKeyTyped(evt);
            }
        });
        jPanel1.add(txtNome);
        txtNome.setBounds(310, 20, 380, 30);

        jPanel2.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("ID:");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(20, 20, 50, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("CEP:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 100, 50, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Telefone:");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(20, 180, 70, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Email:");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(20, 140, 50, 30);

        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField8);
        jTextField8.setBounds(90, 180, 120, 30);

        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField9);
        jTextField9.setBounds(90, 20, 90, 30);

        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField10);
        jTextField10.setBounds(90, 100, 120, 30);

        jTextField11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField11);
        jTextField11.setBounds(90, 140, 120, 30);

        tbCarros1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Classe", "Categoria", "Marca", "Cor", "Ano", "Placa", "Alugado", "Portas", "Preço"
            }
        ));
        jScrollPane3.setViewportView(tbCarros1);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(0, 350, 710, 140);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Endereço:");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(20, 60, 70, 30);

        jTextField12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField12);
        jTextField12.setBounds(90, 60, 600, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Nome:");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(190, 20, 50, 30);

        jTextField13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField13);
        jTextField13.setBounds(240, 20, 450, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Telefone:");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(20, 220, 70, 30);

        jTextField14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField14);
        jTextField14.setBounds(90, 220, 120, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 0, 0);

        txtEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        txtEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEstadoKeyTyped(evt);
            }
        });
        jPanel1.add(txtEstado);
        txtEstado.setBounds(430, 140, 260, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Estado:");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(360, 140, 50, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Celular:");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(20, 180, 70, 30);

        txtCelular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularActionPerformed(evt);
            }
        });
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });
        jPanel1.add(txtCelular);
        txtCelular.setBounds(80, 180, 210, 30);

        txtCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCidadeActionPerformed(evt);
            }
        });
        txtCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCidadeKeyTyped(evt);
            }
        });
        jPanel1.add(txtCidade);
        txtCidade.setBounds(80, 140, 260, 30);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Cidade:");
        jPanel1.add(jLabel24);
        jLabel24.setBounds(20, 140, 50, 30);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Rua:");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(140, 60, 40, 30);

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Sexo:");
        jPanel1.add(jLabel31);
        jLabel31.setBounds(20, 60, 40, 30);

        txtRua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRuaActionPerformed(evt);
            }
        });
        txtRua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRuaKeyTyped(evt);
            }
        });
        jPanel1.add(txtRua);
        txtRua.setBounds(180, 60, 230, 30);

        txtComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtComplementoActionPerformed(evt);
            }
        });
        txtComplemento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtComplementoKeyTyped(evt);
            }
        });
        jPanel1.add(txtComplemento);
        txtComplemento.setBounds(500, 100, 190, 30);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Complemento:");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(400, 100, 100, 30);

        txtPlaca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(txtPlaca);
        txtPlaca.setBounds(800, 380, 80, 30);

        try {
            txtCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });
        txtCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCPFKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPFKeyReleased(evt);
            }
        });
        jPanel1.add(txtCPF);
        txtCPF.setBounds(80, 20, 150, 30);

        cbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(cbSexo);
        cbSexo.setBounds(80, 60, 50, 30);

        btnCancelar.setBackground(new java.awt.Color(204, 204, 204));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(510, 240, 180, 29);

        btnAlterar.setBackground(new java.awt.Color(204, 204, 204));
        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAlterar);
        btnAlterar.setBounds(300, 240, 180, 29);

        btnCadastrar.setBackground(new java.awt.Color(204, 204, 204));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCadastrar);
        btnCadastrar.setBounds(80, 240, 180, 29);

        txtNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        jPanel1.add(txtNumero);
        txtNumero.setBounds(310, 100, 70, 30);

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("Numero:");
        jPanel1.add(jLabel32);
        jLabel32.setBounds(240, 100, 60, 30);

        abas.addTab("Cadastrar", jPanel1);

        jPanel3.setLayout(null);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Dias:");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(270, 140, 80, 30);

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Ano:");
        jPanel3.add(jLabel29);
        jLabel29.setBounds(30, 180, 50, 30);

        lbAno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbAno.setText("...");
        jPanel3.add(lbAno);
        lbAno.setBounds(90, 180, 140, 30);

        lbCor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCor.setText("...");
        jPanel3.add(lbCor);
        lbCor.setBounds(90, 140, 140, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Cor:");
        jPanel3.add(jLabel28);
        jLabel28.setBounds(30, 140, 50, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Classe:");
        jPanel3.add(jLabel27);
        jLabel27.setBounds(30, 100, 50, 30);

        lbClasse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbClasse.setText("...");
        jPanel3.add(lbClasse);
        lbClasse.setBounds(90, 100, 140, 30);

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Marca:");
        jPanel3.add(jLabel34);
        jLabel34.setBounds(30, 60, 50, 30);

        lbMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbMarca.setText("...");
        jPanel3.add(lbMarca);
        lbMarca.setBounds(90, 60, 130, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Categoria:");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(270, 20, 70, 30);

        lbCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbCategoria.setText("...");
        jPanel3.add(lbCategoria);
        lbCategoria.setBounds(370, 20, 160, 30);

        lbTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTotal.setText("...");
        jPanel3.add(lbTotal);
        lbTotal.setBounds(370, 180, 170, 30);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Portas:");
        jPanel3.add(jLabel25);
        jLabel25.setBounds(270, 60, 60, 30);

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Modelo:");
        jPanel3.add(jLabel35);
        jLabel35.setBounds(30, 20, 50, 30);

        lbModelo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbModelo.setText("...");
        jPanel3.add(lbModelo);
        lbModelo.setBounds(90, 20, 150, 30);

        btnAlugar.setBackground(new java.awt.Color(204, 204, 204));
        btnAlugar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlugar.setText("Confirmar Aluguel");
        btnAlugar.setEnabled(false);
        btnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlugarActionPerformed(evt);
            }
        });
        jPanel3.add(btnAlugar);
        btnAlugar.setBounds(190, 240, 320, 40);

        lbPortas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbPortas.setText("...");
        jPanel3.add(lbPortas);
        lbPortas.setBounds(370, 60, 170, 30);

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Total:");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(270, 180, 80, 30);

        cbQtd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));
        cbQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQtdActionPerformed(evt);
            }
        });
        jPanel3.add(cbQtd);
        cbQtd.setBounds(370, 140, 80, 30);

        lbValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbValor.setText("...");
        jPanel3.add(lbValor);
        lbValor.setBounds(370, 100, 170, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Preço Dia:");
        jPanel3.add(jLabel26);
        jLabel26.setBounds(270, 100, 80, 30);

        abas.addTab("Veiculo", jPanel3);

        getContentPane().add(abas);
        abas.setBounds(20, 80, 730, 350);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("Clientes");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 150, 50);

        jMenu1.setText("Opções");

        mnCadastrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        mnCadastrar.setText("Cadastrar");
        mnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastrarActionPerformed(evt);
            }
        });
        jMenu1.add(mnCadastrar);

        mnAlterar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        mnAlterar.setText("Alterar");
        mnAlterar.setEnabled(false);
        mnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlterarActionPerformed(evt);
            }
        });
        jMenu1.add(mnAlterar);

        mnCancelar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnCancelar.setText("Cancelar");
        mnCancelar.setEnabled(false);
        mnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCancelarActionPerformed(evt);
            }
        });
        jMenu1.add(mnCancelar);

        mnAlugar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnAlugar.setText("Confirmar Aluguel");
        mnAlugar.setEnabled(false);
        mnAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAlugarActionPerformed(evt);
            }
        });
        jMenu1.add(mnAlugar);

        mnSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        mnSair.setText("Sair");
        mnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSairActionPerformed(evt);
            }
        });
        jMenu1.add(mnSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(782, 493));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCEPActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstadoActionPerformed

    private void txtCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelularActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Reset do programa
        modoEdicao(true);
        resetCampos();

        // Reset do botao alterar
        btnCadastrar.setEnabled(true);
        mnCadastrar.setEnabled(true);

        btnAlterar.setEnabled(false);
        mnAlterar.setEnabled(false);

        btnCancelar.setEnabled(false);
        mnCancelar.setEnabled(false);

        txtCPF.setText("");
        btnAlterar.setText("Alterar");
        mnAlterar.setText("Alterar");
        edicaoAtiva = false;
        
        btnAlugar.setEnabled(false); // Desabilita aluguel
        mnAlugar.setEnabled(false); // Desabilita aluguel
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCidadeActionPerformed

    private void txtRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRuaActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComplementoActionPerformed

    private void jPanel1ComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentHidden

    }//GEN-LAST:event_jPanel1ComponentHidden

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseClicked

    private void btnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlugarActionPerformed
        AlugadosDAO aluguel = new AlugadosDAO();

        String rs = aluguel.store(gAlugados);

        if (!rs.equals("ok")) {
            JOptionPane.showMessageDialog(null, rs);
            return;
        }

        JOptionPane.showMessageDialog(null, "Veiculo alugado com sucesso!");

        frmAlugados alugados = new frmAlugados();
        alugados.setVisible(true);

        dispose();
    }//GEN-LAST:event_btnAlugarActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    private void txtCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyReleased
        Util map = new Util();

        if (map.cpfIsValid(txtCPF.getText())) {
            Cliente cli = new ClienteDAO().buscaCliente(
                    map.parserCpf(txtCPF.getText())
            );

            try{
            if (cli != null) {
                txtCPF.setText(cli.getCpf());
                txtNome.setText(cli.getNome());
                cbSexo.setSelectedItem(cli.getSexo());
                txtCEP.setText(cli.getCep());
                txtRua.setText(cli.getRua());
                txtBairro.setText(cli.getBairro());
                txtNumero.setText(cli.getNumero());
                txtComplemento.setText(cli.getComplemento());
                txtCidade.setText(cli.getCidade());
                txtEstado.setText(cli.getEstado());
                txtEmail.setText(cli.getEmail());
                txtCelular.setText(cli.getCelular());

                modoEdicao(false); // Bloqueia campos

                btnAlterar.setEnabled(true); // Libera botao
                mnAlterar.setEnabled(true); // Libera botao

                btnCadastrar.setEnabled(false); // Desabilita o cadastro
                mnCadastrar.setEnabled(false); // Desabilita o cadastro

                btnCancelar.setEnabled(true); // Habilita cancelar
                mnCancelar.setEnabled(true); // Habilita cancelar

                btnAlugar.setEnabled(true); // Habilita aluguel
                mnAlugar.setEnabled(true); // Habilita aluguel

                // Globaliza Cliente
                gCliente = cli;

                montaAlugados();

            } else {
                modoEdicao(true); // Libera campos

                resetCampos(); // Reseta os campos (exceto cpf)

                btnAlterar.setEnabled(false); // Desabilita botao
                mnAlterar.setEnabled(false); // Desabilita botao

                btnCadastrar.setEnabled(true); // Libera o cadastro
                mnCadastrar.setEnabled(true); // Libera o cadastro

                btnCancelar.setEnabled(false); // Desabilita cancelar
                mnCancelar.setEnabled(false); // Desabilita cancelar

                btnAlugar.setEnabled(false); // Habilita aluguel
                mnAlugar.setEnabled(false); // Habilita aluguel

                gCliente = null;
            }
            }
            catch(Exception e){
                e.getMessage();
            }

        }
    }//GEN-LAST:event_txtCPFKeyReleased

    private void txtNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyTyped
        if (txtNome.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }

    }//GEN-LAST:event_txtNomeKeyTyped

    private void txtRuaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRuaKeyTyped
        if (txtRua.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtRuaKeyTyped

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if (txtNumero.getText().length() >= 7) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtComplementoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComplementoKeyTyped
        if (txtComplemento.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtComplementoKeyTyped

    private void txtCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCidadeKeyTyped
        if (txtCidade.getText().length() >= 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtCidadeKeyTyped

    private void txtEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEstadoKeyTyped
        if (txtEstado.getText().length() >= 30) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtEstadoKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        if (txtCelular.getText().length() >= 11) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        if (txtEmail.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtCEPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCEPKeyTyped
        if (txtCEP.getText().length() >= 8) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }//GEN-LAST:event_txtCEPKeyTyped

    private void txtBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBairroKeyTyped
        if (txtBairro.getText().length() >= 50) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();

        }
    }//GEN-LAST:event_txtBairroKeyTyped

    private void txtCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPFKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFKeyPressed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        Util map = new Util();

        if (!map.cpfIsValid(txtCPF.getText())) {
            JOptionPane.showMessageDialog(null, "CPF inválido");
        } else if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
        } else if (txtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
        } else if (txtRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
        } else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
        } else if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
        } else {
            Cliente cadastrar = gravaCliente();
            String resp = new ClienteDAO().gravarCliente(cadastrar);
            if (resp == "OK") {
                JOptionPane.showMessageDialog(null, "Cliente " + txtNome.getText() + " Cadastrado");

                resetCampos();
                txtCPF.setText("");
            }
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed


    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Se edicao for false entao cadastrar
        if (!edicaoAtiva) {
            edicaoAtiva = true;
            btnAlterar.setText("Salvar alteração");
            mnAlterar.setText("Salvar alteração");
            modoEdicao(true);
            return;
        }

        // A partir deste excuta a Edição
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
        } else if (txtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
        } else if (txtRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
        } else if (txtComplemento.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher COMPLEMENTO do cliente");
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
        } else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
        } else if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
        } else {
            // Altera o Cliente
            int resp = JOptionPane.showConfirmDialog(this, "Deseja confirmar a alteação?");
            if (resp == JOptionPane.YES_OPTION) {
                String cli = new ClienteDAO().alteraClinte(gravaCliente());
                if (cli == "OK") {
                    JOptionPane.showMessageDialog(null, "Cliente do CPF " + txtCPF.getText() + " Alterado!!!");
                } else {
                    JOptionPane.showMessageDialog(null, cli);
                }
            }

            // Reset do programa
            resetCampos();

            // Reset do botao alterar
            btnCadastrar.setEnabled(true);
            mnCadastrar.setEnabled(true);
            
            btnAlterar.setEnabled(false);
            mnAlterar.setEnabled(false);
            
            btnCancelar.setEnabled(false);
            mnCancelar.setEnabled(false);
            
            txtCPF.setText("");
            btnAlterar.setText("Alterar");
            mnAlterar.setText("Alterar");
            edicaoAtiva = false;
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void cbQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQtdActionPerformed
        montaAlugados();
    }//GEN-LAST:event_cbQtdActionPerformed

    private void mnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSairActionPerformed
        dispose();
    }//GEN-LAST:event_mnSairActionPerformed

    private void mnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastrarActionPerformed
        Util map = new Util();

        if (!map.cpfIsValid(txtCPF.getText())) {
            JOptionPane.showMessageDialog(null, "CPF inválido");
        } else if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
        } else if (txtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
        } else if (txtRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
        } else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
        } else if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
        } else {
            Cliente cadastrar = gravaCliente();
            String resp = new ClienteDAO().gravarCliente(cadastrar);
            if (resp == "OK") {
                JOptionPane.showMessageDialog(null, "Cliente " + txtNome.getText() + " Cadastrado");

                resetCampos();
                txtCPF.setText("");
            }
        }
    }//GEN-LAST:event_mnCadastrarActionPerformed

    private void mnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlterarActionPerformed
       // Se edicao for false entao cadastrar
        if (!edicaoAtiva) {
            edicaoAtiva = true;
            btnAlterar.setText("Salvar alteração");
            mnAlterar.setText("Salvar alteração");
            modoEdicao(true);
            return;
        }

        // A partir deste excuta a Edição
        if (txtNome.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NOME do cliente");
        } else if (txtCEP.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CEP do cliente");
        } else if (txtRua.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher RUA do cliente");
        } else if (txtBairro.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher BAIRRO do cliente");
        } else if (txtNumero.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher NUMERO do cliente");
        } else if (txtCidade.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CIDADE do cliente");
        } else if (txtEstado.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher ESTADO do cliente");
        } else if (txtEmail.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher EMAIL do cliente");
        } else if (txtCelular.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencher CELULAR do cliente");
        } else {
            // Altera o Cliente
            int resp = JOptionPane.showConfirmDialog(this, "Deseja confirmar a alteação?");
            if (resp == JOptionPane.YES_OPTION) {
                String cli = new ClienteDAO().alteraClinte(gravaCliente());
                if (cli == "OK") {
                    JOptionPane.showMessageDialog(null, "Cliente do CPF " + txtCPF.getText() + " Alterado!!!");
                } else {
                    JOptionPane.showMessageDialog(null, cli);
                }
            }

            // Reset do programa
            resetCampos();

            // Reset do botao alterar
            btnCadastrar.setEnabled(true);
            mnCadastrar.setEnabled(true);
            
            btnAlterar.setEnabled(false);
            mnAlterar.setEnabled(false);
            
            btnCancelar.setEnabled(false);
            mnCancelar.setEnabled(false);
            
            txtCPF.setText("");
            btnAlterar.setText("Alterar");
            mnAlterar.setText("Alterar");
            edicaoAtiva = false;
            
            btnAlugar.setEnabled(false); // Desabilita aluguel
            mnAlugar.setEnabled(false); // Desabilita aluguel
        }
    }//GEN-LAST:event_mnAlterarActionPerformed

    private void mnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCancelarActionPerformed
// Reset do programa
        modoEdicao(true);
        resetCampos();

        // Reset do botao alterar
        btnCadastrar.setEnabled(true);
        mnCadastrar.setEnabled(true);

        btnAlterar.setEnabled(false);
        mnAlterar.setEnabled(false);

        btnCancelar.setEnabled(false);
        mnCancelar.setEnabled(false);

        txtCPF.setText("");
        btnAlterar.setText("Alterar");
        mnAlterar.setText("Alterar");
        edicaoAtiva = false;
        
        btnAlugar.setEnabled(false); // Desabilita aluguel
        mnAlugar.setEnabled(false); // Desabilita aluguel
    }//GEN-LAST:event_mnCancelarActionPerformed

    private void mnAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAlugarActionPerformed
        AlugadosDAO aluguel = new AlugadosDAO();

        String rs = aluguel.store(gAlugados);

        if (!rs.equals("ok")) {
            JOptionPane.showMessageDialog(null, rs);
            return;
        }

        JOptionPane.showMessageDialog(null, "Veiculo alugado com sucesso!");

        frmAlugados alugados = new frmAlugados();
        alugados.setVisible(true);

        dispose();
    }//GEN-LAST:event_mnAlugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane abas;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlugar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbQtd;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbClasse;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbPortas;
    private javax.swing.JLabel lbTotal;
    private javax.swing.JLabel lbValor;
    private javax.swing.JMenuItem mnAlterar;
    private javax.swing.JMenuItem mnAlugar;
    private javax.swing.JMenuItem mnCadastrar;
    private javax.swing.JMenuItem mnCancelar;
    private javax.swing.JMenuItem mnSair;
    private javax.swing.JTable tbCarros1;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtComplemento;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JLabel txtPlaca;
    private javax.swing.JTextField txtRua;
    // End of variables declaration//GEN-END:variables
}
